### ISSUE TITLE
licence is not clear

### ISSUE THREAD

**Issue by keywan-ghadami-oxid** [acirtautas/oxid-module-internals#18]
Hi, i would like to maintain this module, but 
i can't find any word about the license. So using this module has the risk, that you or any contributes may come up with fees of any kind. I do not think that this was/is your intension, but other users may get afraid and stop using this great module.

I would suggest to use MIT, BOOST, or LGPL for this project.
The problem without having a license is described here:
https://help.github.com/articles/open-source-licensing/

Please add a license.

**Comment by acirtautas** [comment]
Hi, this license question ir really bugging me for a long time, that's why it is still missing.

I promisse to figure it all out.

**Comment by jkrug** [comment]
Why not simply MIT License: Use it in CE / PE / EE projects but keep the authors named?

**Comment by acirtautas** [comment]
@kermie can you help me a bit with this?

**Comment by keywan-ghadami-oxid** [comment]
you are not alone with that problem,
this helped me a bit http://choosealicense.com/

**Comment by kermie** [comment]
Sure I can help sorting it out. Give me some time until after this weekend, am presently on the road.

**Comment by kermie** [comment]
Here we go. 

I'd like to point you to [https://oxidforge.org/en/gplv3-faq](https://oxidforge.org/en/gplv3-faq). This is basically OXID's understanding of the GPLv3 and we should definitely be geared to it.

In short it says that a non-standalone module which overwrites classes and methods of a piece of software like OXID eShop CE has to be treated as derived work. In this manner - as CE is licensed under GPLv3 - the module inherits this license if it shall be published open source. Maybe there are other compatible licenses but I am personally not sure if they are in compliance with this case. 

IMO, there's nothing against using this module (if it is under GPLv3) in a commercial project or in propriety software. 

So I clearly suggest to go for GPLv3 in this case.

@acirtautas, if you want to hand over this repository to another maintainer, most likely the best choice would be to move it to the community organization [OXIDprojects](https://github.com/OXIDprojects/) which collects all these kind of modules. I could add a team which cares about this module and add @keywan-ghadami-oxid, you (if you're still interested) and some other helping hands to this team as contributors with write access.

Cheers!

**Comment by kermie** [comment]
Alf, any decisions yet? @acirtautas

**Comment by kermie** [comment]
@acirtautas you're still around? Peeps coming up and want to port this module for V6. This is still impossible (officially) as the license question is not clarified yet. Cheers!

**Comment by acirtautas** [comment]
Hi @kermie  I am still alive and am grateful for the effort you have put in the license description.

**Comment by kermie** [comment]
Thank you very much, @acirtautas . Hope you're doing well, let's stay in touch via FB ;)
